name: Monthly Retrain River Model

on:
  schedule:
    - cron: '0 0 * * 0'  # Runs every week
  workflow_dispatch:        # Allow manual trigger hahahahahah
jobs:
  retrain:
    runs-on: ubuntu-latest
    env:
      HF_API_KEY: ${{ secrets.HF_API_KEY }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m venv cpfinal
          source cpfinal/bin/activate
          pip install -r requirements.txt

      - name: Run retraining script
        run: |
          source cpfinal/bin/activate
          python -m src.model.train

      - name: Commit updated model
        run: |
          git config user.name "theboredflamingo"
          git config user.email "stuthi.shrisha@gmail.com"
          git stash --include-untracked
          git pull --rebase origin master
          git stash pop || true
          git add src/data/feat.csv src/data/targ.csv src/model/rm11.pkl
          git commit -m "Auto-retrained model and new datasets"
          git push origin master
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
